### ISSUE TITLE
[BUG] SSL context not passed to httpx

### ISSUE THREAD

**Issue by hersonoliveira** [h2oai/cloud-discovery-py#104]
**Description**
discovery client supports ssl context on client init but this setting is not passed to httpx client

https://github.com/h2oai/cloud-discovery-py/blob/main/src/h2o_discovery/_internal/client.py#L40
https://github.com/h2oai/cloud-discovery-py/blob/main/src/h2o_discovery/_internal/client.py#L46

**Steps to reproduce**
This can be tested on an environment that uses private CA

```
import ssl
import h2o_discovery

context = ssl.create_default_context(cafile="rootCA.pem")

client = h2o_discovery.discover(
    environment="https://34.90.224.189.nip.io/", ssl_context=context
)
print(client)
```

**Environment**
h2o-cloud-discovery==2.1.0
https://34.90.224.189.nip.io/ - this env uses private CA, I don't guarantee it's always up. I can send you the certificate if needed

**Comment by zoido** [comment]
Thanks for reporting.
