### ISSUE TITLE
Clear error message if service is unavailable

### ISSUE THREAD

**Issue by mtanco** [h2oai/cloud-discovery-py#23]
When we publish new versions of @h2oai/haic-tutorials that use the discovery service, it's likely that a customer who has not yet upgraded will at some point attempt to run `h2o_discover.discover()` in an environment that does not have the service. 

I just tried this in internal.dedicated.h2o.ai and got `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`. It would be nice if this was a clear message explaining that the service was not available.

**Comment by zoido** [comment]
This particular one is tricky. Request is served by appstore so we get the data but not the correct one. I'll try to figure out some heuristic to have more user-friendly error.

Thanks for reporting.
